/**
 * ICS4U0 Computer Science, Grade 12
 * @fileame SleepCalculator.java
 * @author Ajinkya
 * @date September 24, 2020
 * @modified October 9, 2020
 * @version 2.0
 * @Description: application that calculates the number of hours a person 
 * has spent sleeping from the time [s]he was born until today.
 * It accounts for leap year, 30/31 days a month, auto-sets current date
 * and doesn't allow user to enter current date or a date in future
 */

import java.util.Calendar;
import java.util.Date;
import java.util.TimeZone;
import java.time.LocalDate;
import java.time.temporal.ChronoUnit;

public class SleepCalculator extends javax.swing.JFrame {

    /**
     * Creates new form SleepCalculator
     */
    public SleepCalculator() {
        Calendar calendar = Calendar.getInstance(TimeZone.getDefault());
        int day = calendar.get(Calendar.DATE);
        int month = calendar.get(Calendar.MONTH) + 1;// note: +1 the month for current month
        int year = calendar.get(Calendar.YEAR);

        
        initComponents();
        
        
        toYear.setText(String.valueOf(year));
        toMonth.setText(String.valueOf(month));
        toDay.setText(String.valueOf(day));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        biDay = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        biMonth = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        biYear = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        toMonth = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        toYear = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        toDay = new javax.swing.JTextField();
        calculate = new javax.swing.JButton();
        exit = new javax.swing.JButton();
        displayTotalDays = new javax.swing.JTextField();
        displayTotalHours = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        statusDisplay = new javax.swing.JTextField();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 51, 51));
        jLabel1.setText("Sleep Calculator");

        jLabel2.setText("Enter Your Birthdate");

        jLabel3.setText("Enter Today's Date");

        jLabel4.setText("Day");

        biDay.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BiDayActionPerformed(evt);
            }
        });

        jLabel5.setText("Month");

        jLabel6.setText("Year");

        biYear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BiYearActionPerformed(evt);
            }
        });

        jLabel7.setText("Month");
        
        toMonth.setEditable(false);
        toMonth.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ToMonthActionPerformed(evt);
            }
        });

        jLabel8.setText("Year");
        
        toYear.setEditable(false);
        toYear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ToYearActionPerformed(evt);
            }
        });

        jLabel9.setText("Day");
        
        toDay.setEditable(false);
        toDay.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ToDayActionPerformed(evt);
            }
        });

        calculate.setText("Calculate");
        calculate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CalculateActionPerformed(evt);
            }
        });

        exit.setText("Exit");
        exit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ExitActionPerformed(evt);
            }
        });

        displayTotalDays.setEditable(false);
        displayTotalDays.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DisplayTotalDaysActionPerformed(evt);
            }
        });

        displayTotalHours.setEditable(false);
        displayTotalHours.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DisplayTotalHoursActionPerformed(evt);
            }
        });

        jLabel10.setText("Status");

        statusDisplay.setEditable(false);
        statusDisplay.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                StatusDisplayActionPerformed(evt);
            }
        });

        jMenu1.setText("File");
        jMenuBar1.add(jMenu1);

        jMenu2.setText("Edit");
        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(39, 39, 39)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(biDay, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(jLabel5)
                                        .addGap(7, 7, 7))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel6)
                                        .addGap(15, 15, 15)))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(biYear)
                                    .addComponent(biMonth, javax.swing.GroupLayout.DEFAULT_SIZE, 60, Short.MAX_VALUE))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 67, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(toDay, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel7)
                                    .addComponent(jLabel8))
                                .addGap(7, 7, 7)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(toYear)
                                    .addComponent(toMonth, javax.swing.GroupLayout.DEFAULT_SIZE, 60, Short.MAX_VALUE))))
                        .addGap(71, 71, 71))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(exit, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(calculate))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(displayTotalDays)
                            .addComponent(displayTotalHours))))
                .addGap(24, 24, 24))
            .addGroup(layout.createSequentialGroup()
                .addGap(105, 105, 105)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel10)
                .addGap(18, 18, 18)
                .addComponent(statusDisplay, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(118, 118, 118))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(biDay, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(biMonth, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(19, 19, 19)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(biYear, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel9)
                            .addComponent(toDay, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(toMonth, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(19, 19, 19)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8)
                            .addComponent(toYear, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(calculate)
                    .addComponent(displayTotalDays, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(12, 12, 12)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(exit)
                    .addComponent(displayTotalHours, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(statusDisplay, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(16, Short.MAX_VALUE))
        );
        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BiDayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BiDayActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BiDayActionPerformed

    private void BiYearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BiYearActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BiYearActionPerformed

    private void ToYearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ToYearActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ToYearActionPerformed

    private void ToDayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ToDayActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ToDayActionPerformed

    private void ToMonthActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ToMonthActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ToMonthActionPerformed

    private void CalculateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CalculateActionPerformed
        int  bDay, bMonth, bYear, tDay, tMonth, tYear;
        Long totalDays, totalSleep;
        
        
        try{ 
            bDay = Integer.parseInt(biDay.getText());
            bMonth = Integer.parseInt(biMonth.getText());
            bYear = Integer.parseInt(biYear.getText());
            tDay = Integer.parseInt(toDay.getText());
            tMonth = Integer.parseInt(toMonth.getText());
            tYear = Integer.parseInt(toYear.getText());
            
            
            // parsing the date
            LocalDate dateBefore = LocalDate.of(bYear, bMonth, bDay);
            LocalDate dateAfter = LocalDate.of(tYear, tMonth, tDay);
            
            
            // checks all text cases: birth month <= 12, negative int, zeros 
            // and if present year is after than birth year.
            if(dateBefore.isBefore(dateAfter)){
                if(bDay >=1 &&(bMonth <= 12 && bMonth >= 1)&& bYear >= 1){
                    
                    totalDays = ChronoUnit.DAYS.between(dateBefore, dateAfter);
                    totalSleep = totalDays*8;

                    
                    displayTotalDays.setText("YOU HAVE SURVIVED FOR " + Long.toString(totalDays) + " DAYS.");
                    displayTotalHours.setText("YOU HAVE SLEPT FOR " + Long.toString(totalSleep) + " HOURS."); 
                    statusDisplay.setText("SUCCESSFUL!");
                    
                }else{
                    
                    statusDisplay.setText("FAILED!");
                    System.out.println("Please Ener Valid Credintials In All Fields");
                }
            }else{
                statusDisplay.setText("FAILED!");
                System.out.println("Birth Date Should Be Before Todays Date!");
            }
            
        }catch(IllegalArgumentException e){
            statusDisplay.setText("FAILED!");
            System.out.println("Please Enter A Number!");
        }catch(java.time.DateTimeException e){
            statusDisplay.setText("FAILED!");
            System.out.println("Please Enter Valid Credentials!");
        }catch(Exception e){
            statusDisplay.setText("FAILED!");
            System.out.println("There Was An Error!");
        }
    }//GEN-LAST:event_CalculateActionPerformed

    private void ExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ExitActionPerformed
        System.exit(0);
    }//GEN-LAST:event_ExitActionPerformed

    private void DisplayTotalDaysActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DisplayTotalDaysActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_DisplayTotalDaysActionPerformed

    private void DisplayTotalHoursActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DisplayTotalHoursActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_DisplayTotalHoursActionPerformed

    private void StatusDisplayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_StatusDisplayActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_StatusDisplayActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SleepCalculator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SleepCalculator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SleepCalculator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SleepCalculator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SleepCalculator().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField biDay;
    private javax.swing.JTextField biMonth;
    private javax.swing.JTextField biYear;
    private javax.swing.JButton calculate;
    private javax.swing.JTextField displayTotalDays;
    private javax.swing.JTextField displayTotalHours;
    private javax.swing.JButton exit;
    private javax.swing.JTextField statusDisplay;
    private javax.swing.JTextField toDay;
    private javax.swing.JTextField toMonth;
    private javax.swing.JTextField toYear;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    // End of variables declaration//GEN-END:variables
}
