
/**
 * ICS4U0 Computer Science, Grade 12
 * @fileame StudentGrades.java
 * @author Ajinkya
 * @date October 12, 2020
 * @version 1.0
 * @Description: A Student Grades Application that simulates a grade book for 
 * a class with 15 students who each have four test scores(upto 2 decimal  
 * places). It has functionality to add students with their marks, list the
 * student data, display average of a student by name and display the course
 * average for each of the courses.
 */

public class StudentGrades extends javax.swing.JFrame {
    
    // Setting up a 2D array
    String [ ][ ] db = new String [15][5];
    int count = 0;   
    /**
     * Creates new form StudentGrades
     */
    public StudentGrades() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        usrFName = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        usrLName = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        tst1 = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        tst2 = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        tst3 = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        tst4 = new javax.swing.JTextField();
        addBtn = new javax.swing.JButton();
        listBtn = new javax.swing.JButton();
        studentAvg = new javax.swing.JButton();
        courseAvg = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        displayDB = new javax.swing.JTextArea();
        exitBtn = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        statusDisplay = new javax.swing.JTextField();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 3, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 0, 0));
        jLabel1.setText("Student Grades");

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel2.setText("First Name:");

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel3.setText("Last Name:");

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel4.setText("Test 1");

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel5.setText("Test 2");

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel6.setText("Test 3");

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel7.setText("Test 4");

        addBtn.setText("ADD");
        addBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addBtnActionPerformed(evt);
            }
        });

        listBtn.setText("LIST");
        listBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                listBtnActionPerformed(evt);
            }
        });

        studentAvg.setText("Student Average");
        studentAvg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                studentAvgActionPerformed(evt);
            }
        });

        courseAvg.setText("Course Average");
        courseAvg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                courseAvgActionPerformed(evt);
            }
        });

        displayDB.setEditable(false);
        displayDB.setColumns(20);
        displayDB.setRows(5);
        jScrollPane1.setViewportView(displayDB);

        exitBtn.setText("EXIT");
        exitBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitBtnActionPerformed(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel8.setText("STATUS");

        statusDisplay.setEditable(false);
        statusDisplay.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        statusDisplay.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                statusDisplayActionPerformed(evt);
            }
        });


        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(64, 64, 64)
                                        .addComponent(exitBtn))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(33, 33, 33)
                                        .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(statusDisplay, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(tst4, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(tst2, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(tst1, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(tst3, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(86, 86, 86)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(addBtn)
                                    .addComponent(listBtn))
                                .addGap(91, 91, 91)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(courseAvg, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(studentAvg, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(33, 33, 33))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(usrFName, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(usrLName, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(56, 56, 56)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(185, 185, 185))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(usrFName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(usrLName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(tst1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(addBtn)
                    .addComponent(studentAvg))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(tst2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(tst3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(listBtn)
                    .addComponent(courseAvg))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(tst4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 235, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(exitBtn)
                        .addGap(78, 78, 78)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(statusDisplay, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(29, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>                        
    
    private void listAll(){
        try{
            
            displayDB.setText("");
            
            
            // Goes through each element in the 2d array and appends each 
            // element to the text area
            for(int i=0; i<count; i++){
                for(int j=0; j<db[0].length; j++){
                    if(j == 0){
                        displayDB.append(db[i][j] + ": ");
                    }else{
                        displayDB.append(db[i][j] + ", ");
                    }
                }
                displayDB.append("\n");
            }
            
            
            statusDisplay.setText("SUCCESSFUL");
            
        }catch(Exception e){
            statusDisplay.setText("FAILED");
            System.out.println("There Was An Unknown Error!");
        }
    }
    
    private void addBtnActionPerformed(java.awt.event.ActionEvent evt) {                                       
        // TODO add your handling code here:
        try{
        
            String fName, lName, test1, test2, test3, test4;
            double t1, t2, t3, t4;


            // Getting values from the user
            fName = usrFName.getText().trim();
            lName = usrLName.getText().trim();
            test1 = tst1.getText();
            test2 = tst2.getText();
            test3 = tst3.getText();
            test4 = tst4.getText();


            // Checking if the user given values ar valid doubles through 
            // exception handling, by conveting String to Doubles
            t1 = Double.parseDouble(test1) * 100;
            t2 = Double.parseDouble(test2) * 100;
            t3 = Double.parseDouble(test3) * 100;
            t4 = Double.parseDouble(test4) * 100;
            
            if (!"".equals(fName)){
                // check to make sure if all test scores are upto 2 decimal places
                if((t1-(int)t1) == 0 && (t2-(int)t2) == 0 && (t3-(int)t3) == 0 && (t4-(int)t4) == 0){

                    // checks for any negative mark
                    if(t1>=0 && t1/100<=100 && t2>=0 && t2/100<=100 && t3>=0 && t3/100<=100 && t4>=0 && t4/100<=100){

                        // Finally adding values to array
                        db[count][0] = fName + " " + lName;
                        db[count][1] = test1;
                        db[count][2] = test2;
                        db[count][3] = test3;
                        db[count][4] = test4; // [[name, t1, t1, t3, t4],[...], ....]
                        count ++;

                        
                        listAll();

                    }else{
                        statusDisplay.setText("FAILED");
                        System.out.println("Please Enter A Valid Test Mark!");
                    }
                }else {
                    statusDisplay.setText("FAILED!");
                    System.out.println("Please Enter An Amount In Correct Format!");
                }
            }else{
                statusDisplay.setText("FAILED!");
                System.out.println("Please Fill The First And Last Name!");
            }
            
            
        }catch(IllegalArgumentException e){
            statusDisplay.setText("FAILED");
            System.out.println("Please Enter A Number As A Test Mark!");
        }catch(ArrayIndexOutOfBoundsException e){
            statusDisplay.setText("FAILED");
            System.out.println("Maximum Capacity Reached For The Student Database!");
        }catch(Exception e){
            statusDisplay.setText("FAILED");
            System.out.println("There Was An Unknown Error!");
        }
    }                                      

    private void listBtnActionPerformed(java.awt.event.ActionEvent evt) {                                        
        // TODO add your handling code here:
        listAll();
    }                                       

    private void courseAvgActionPerformed(java.awt.event.ActionEvent evt) {                                          
        // TODO add your handling code here:
        try{
            
            double average1, average2, average3, average4, total1, total2, total3, total4;
            String t = "";
            
            
            total1 = 0;
            total2 = 0;
            total3 = 0;
            total4 = 0;
            displayDB.setText("");
            
            
            for(int i=0; i<count; i++){
                for(int j=0; j<db[0].length; j++){
                    
                    if(j == 0){
                        t += db[i][j] + ": ";
                    }else{
                        t += db[i][j] + ", ";
                    }
                    
                    // adds mark to the specific total var
                    // (test1 --> total1, test2 --> total2, ...)
                    switch (j) {
                        case 1:
                            total1 += Double.parseDouble(db[i][j]);
                            break;
                        case 2:
                            total2 += Double.parseDouble(db[i][j]);
                            break;
                        case 3:
                            total3 += Double.parseDouble(db[i][j]);
                            break;
                        case 4:
                            total4 += Double.parseDouble(db[i][j]);
                            break;
                        default:
                            break;
                    }
                }
                t += "\n";
            }

            
            average1 = total1/count;
            average2 = total2/count;
            average3 = total3/count;
            average4 = total4/count;

            
            // Output averages and all student info to the textArea
            displayDB.append("Test1 Avg: " + Double.toString(Math.round (average1*100.0)/100.0) + "\n");
            displayDB.append("Test2 Avg: " + Double.toString(Math.round (average2*100.0)/100.0) + "\n");
            displayDB.append("Test3 Avg: " + Double.toString(Math.round (average3*100.0)/100.0) + "\n");
            displayDB.append("Test4 Avg: " + Double.toString(Math.round (average4*100.0)/100.0) + "\n\n");
            displayDB.append(t);
            statusDisplay.setText("SUCCESSFUL");
            
        }catch(Exception e){
            statusDisplay.setText("FAILED");
            System.out.println("There Was An Unknown Error!");
        }
        
    }                                         

    private void exitBtnActionPerformed(java.awt.event.ActionEvent evt) {                                        
        // TODO add your handling code here:
        System.exit(0);
    }                                       

    private void studentAvgActionPerformed(java.awt.event.ActionEvent evt) {                                           
        // TODO add your handling code here:
        try{
            String userWName, uF, uL;
            double average, total;

            
            displayDB.setText("");
            uF = usrFName.getText().trim();
            uL = usrLName.getText().trim();
            
            
            // checks if user entered student name
            if (!"".equals(uF)){
                userWName = uF + " " + uL;

                for(int i=0; i<count; i++){   
                    if(db[i][0].equals(userWName)){ // ckecks if the array contains student name

                        total = 0; // initilizing total to zero in here in case there are multiple students with same name
                        displayDB.append(userWName + ": ");

                        for(int j=1; j<db[0].length; j++){
                            if(j == 0){
                                displayDB.append(db[i][j] + ": ");
                            }else{
                                displayDB.append(db[i][j] + ", ");
                            }
                            total += Double.parseDouble(db[i][j]); // incrementing the total by each test mark of the student
                        }


                        average = total/4;
                        displayDB.append("\nAvg: " + Double.toString(Math.round (average*100.0)/100.0) + "\n\n");
                    }
                }
            statusDisplay.setText("SUCCESSFUL");
            }else{
                statusDisplay.setText("FAILED");
                System.out.println("Please Fill The First And Last Name!");
            }
            
        }catch(Exception e){
            statusDisplay.setText("FAILED");
            System.out.println("There Was An Unknown Error!");
        }
    }                                          

    private void statusDisplayActionPerformed(java.awt.event.ActionEvent evt) {                                              
        // TODO add your handling code here:
    }                                             

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(StudentGrades.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(StudentGrades.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(StudentGrades.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(StudentGrades.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new StudentGrades().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify                     
    private javax.swing.JButton addBtn;
    private javax.swing.JButton courseAvg;
    private javax.swing.JTextArea displayDB;
    private javax.swing.JButton exitBtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton listBtn;
    private javax.swing.JTextField statusDisplay;
    private javax.swing.JButton studentAvg;
    private javax.swing.JTextField tst1;
    private javax.swing.JTextField tst2;
    private javax.swing.JTextField tst3;
    private javax.swing.JTextField tst4;
    private javax.swing.JTextField usrFName;
    private javax.swing.JTextField usrLName;
    // End of variables declaration                   
}
